builds:
  - binary: motionctrl
    goos:
      - linux
    goarch:
      - amd64
      - 386
      - arm
      - arm64
      - mips
      - mipsle
      - mips64
      - mips64le
      - s390x	

release:
  prerelease: true