language: go

sudo: true
dist: trusty

go:
  - 1.10.x

# Required from Goreleaser
addons:
  apt:
    packages:
    - snapd
    - rpm
    - snapcraft

# Required from Goreleaser
env:
- PATH=/snap/bin:$PATH

before_install:
  - sudo apt-get install autoconf automake build-essential pkgconf libtool git libzip-dev libjpeg-dev
  - sudo apt-get install libavformat-dev libavcodec-dev libavutil-dev libswscale-dev libavdevice-dev
  - sudo apt-get install libjpeg-turbo8 libjpeg-turbo8-dev
  - sudo apt-get install libwebp-dev
  - git clone https://github.com/Motion-Project/motion.git motion-release
  - cd motion-release
  - git checkout $(git ls-remote --tags https://github.com/Motion-Project/motion.git | awk '{print $2}' | grep -v '{}' | awk -F"/" '{print $3}' | tail -n 1)
  - autoreconf -fiv
  - ./configure
  - make
  - sudo make install
  - cd ..
  - rm -rf motion-release

go_import_path: github.com/andreacioni/motionctrl

# Required from Goreleaser
install:
- sudo snap install snapcraft --classic

# Required from Goreleaser
services:
- docker

# Required from Goreleaser
deploy:
- provider: script
  skip_cleanup: true
  script: curl -sL http://git.io/goreleaser | bash
  on:
    tags: true
    condition: $TRAVIS_OS_NAME = linux